### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by laurelsilva**
Updating `README.md` with steps to install the theme! 😄

### CODE REVIEW

**Comment by aaronjensen** [comment]
Thank you! Because the theme is on MELPA, I'd rather reference that fact. If folks aren't using MELPA, they probably know how to manually install a theme. Also, the instructions you provided are opinionated and I'd rather allow people to make their own choices about where and how they install things.

**Comment by laurelsilva** [comment]
I agree. What's the correct approach to documenting the installation? Make explicit how to install this theme. In my specific case, I was not aware that you could install it through MELPA.

**Comment by aaronjensen** [comment]
I've addressed this in 4b9b5cb, borrowing copy from another theme.

**Comment by aaronjensen** [comment]
Closing this out. Thanks again for bringing this to my attention.

**Pull request closed without merging**
